spring.application.name=jeopardy
spring.datasource.url=jdbc:postgresql://localhost:5432/jeopardydb
spring.datasource.username=postgres
spring.datasource.password=passwd985627

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true